language: go

go:
- 1.12

go_import_path: github.com/narrowizard/cerise

branches:
  only:
  - master

env:
  global:
    - secure: "nS7kbuJRfFWTxeJ2ZAu31h3TR3kU4Dse0hYj0AWhmmEfmo1jjPsfOnySGCj616SSliFz+FruxiNbXTA4lBsEsiJ0FXeZk9+gDt2a0Zw1RvQm0eVzgH2QMjpJdpdOd/shVgYhtvL4C1VAJTyGI2NGYjOcEI009gCfqgfSRRJ7YEaAuPwEQvSTKj+/kj/qbODi42vGx80+t1JuN9tAM4kU/392qKbNGAHAxSkBsGi2QD3fpmGlDhvXACDIKw16t4YZYYnqqOXQFqb5IYcof+OdUgjOQxdXKDgtd3l56CK7cSDnQhWM9qBkQCSHbAPSoFGcQFLRv9CGKGsMArOrN+xP6ESyIhtD8KsDDCYpuNDxiKPwgIigOZKO9FY9/fAN74P2YXTEwRj5I+AGIt0qyS2vdemeVimRNneRfkkpNrONAlLmo1VIW3mNk1UPR1+iElzQo9u2mjNcfXCc96kmYVCPqxjrLgcL97PwMaSk4XWPXxfgjeebvgCTppCf9Ix7gdXrMohZwBNTnJItoSnCsW3C/Gt98X4AzbiuVsCps0V3ZAKWIikJR/f1/bz0NYGayKjvcgsrFZOWEO6iNTflTChh0+Tw1os2YQxscEgIYIB2P2LMM8SUtAty7/y5P/uPLFpqZumW7kOIYzqFLt5i83NRwqzUg3cuoNAmTYG8Y6Slcoo="
    - secure: "Nfd1G08FvGNVMoE3DUwUm188k/VNxh/YQ+BdVpxXN/j5Lp1fsTfpJq/UAFb6npp90K/VWafWcNFaDhe+qhjcqZwq9XsjeB7bT/YBhckOkwngtLjiU268tadzvrUYsQ28xBfeB/Gf/R89+S4ph3GPk5g39Al/zLB2apDR+4XOtxULV8upBuaWIsexB1RVseTrY75po25qNVklyFfL0hCngqqYpIkrBchFLnWgXnx1gfE/8nO9upVYFRM2jSeYmsXjHIUp29ZD72vR+sRK03RJQ7ZMC1Irxno9FjUd7lIY3fMBNOnD3eI5tnzPQI0KM08iUJsZVZwatBa11kM+P9L3qaH0owFwsRoGWyLsXk+WlIp9NgOJ7hVt4g0kCDj8P1+mkoWyV0BWo0IgBRR+tyiRZMqaWPN3ld2/NNiEhX5GtjzI4htae0YqYkXY2kPSn4N0fofuhxNB3M2zY7XQNYMV/0i5JemQV3CKK9JlWkkejF6e9sNEhbs1wZDNYsDu1OiILidYQkfBd4W2kyV5CE6kR/vPmoWNFRqsliMKIFlEDaaoIlzBWzSzXnZv3taN8N5m5tPRY9oM0UaLqHuEqHUnuxZz4n+5D5WYuuEgtFh3byaF2pR+CT8tZFP14rHI10EghO+PFfDy0hq7kiSCN9GLQ8A0lowF8XQcRDEd+1rQPZI="
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=narrowizard/cerise
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO